### ISSUE TITLE
Update footer template part

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#27]
Update the footer template part so that it matches the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020070%3A2923) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020113%3A1706) designs. Example PR [here](https://github.com/Automattic/themes/pull/6488) and [here](https://github.com/Automattic/themes/pull/6564).

In the screenshots below:
- We should use the navigation block for all the links, even the social ones.
- For the social links, we can link to `#`. The user can replace them with valid URLs.
- "A Really Long Site Title" and "Cours" are the site title.
- "Course Theme" should not be a link. Instead, "Sensei" should be a link.

## Desktop
![Screen Shot 2022-10-11 at 3 11 30 PM](https://user-images.githubusercontent.com/1190420/195178777-f1c6e8a4-543f-475e-898b-ec708c9388aa.jpg)

## Mobile
![Screen Shot 2022-10-11 at 3 10 56 PM](https://user-images.githubusercontent.com/1190420/195178798-95947c9d-806d-462a-9f39-5f2978b4e4a7.jpg)

#### Scenario: Footer
**Given** The Sensei theme is activated
**When** I view a page
**Then** the footer looks similar to the design on both desktop and mobile
**And** clicking on a page should take you to the URL that the user configured for that page
**And** clicking on a social network should take you to the URL that the user configured for that social network
**And** clicking on Sensei goes to https://senseilms.com/
**And** clicking on WordPress goes to https://wordpress.org.

**Comment by Imran92** [comment]
Hi @donnapep @Luchadores 👋 Just a couple of questions about the design here. For the site title at the bottom, what's the expected font size? For desktop, it seems there are two in the design

![Image](https://user-images.githubusercontent.com/6820724/199120700-f98e891d-219d-43a8-8d8a-efa065013bc2.png)

Is the goal to make the font size grow or shrink automatically to take the whole width (1000px) without line breaking? As site title is a dynamic content, the text length may vary. So we'll have to determine the font size dynamically, probably with JS in that case.

And is the bottom part containing "Course Theme by Sensei.." text, is it sticky at the bottom?

Also, as we are using the Navigation block for containing every link, I'm not sure we we can add the links themselves in the patterns. Because it seems navigation block only keeps an id reference to **Navigation Menu** post type (like `<!-- wp:navigation {"ref":2383} /-->` ) and the referred post contains the actual data (in this case, the URLs of the nav block). So the data probably doesn't actually stay in the pattern markup (In case I haven't missed a way to keep it in the markup). In this case, it will show the users the navigation menu the user have instead of the ones like "YouTube", "Instagram" etc that we want to show

**Comment by Luchadores** [comment]
Hey @Imran92, regarding the Design, this is what I can answer:

> Is the goal to make the font size grow or shrink automatically to take the whole width (1000px) without line breaking? As site title is a dynamic content, the text length may vary. So we'll have to determine the font size dynamically, probably with JS in that case.

Yes. The Site title should always span the entire width. If it's getting longer, the text size should get smaller to fit in the space.

> And is the bottom part containing "Course Theme by Sensei.." text, is it sticky at the bottom?

I don't really get how this can be sticky at the bottom. I don't believe it is. It just behaves normally, like a part of the footer. For example, if the title gets smaller, the space in-between the title and "Course Theme by Sensei..." should always be the same. Similar to the design mockup. 

Hope this helps 👋

**Comment by Imran92** [comment]
Thanks for answers @Luchadores 🌻 

> Yes. The Site title should always span the entire width. If it's getting longer, the text size should get smaller to fit in the space.

Great, just had to make sure that this is an expected behavior because making the font size work that way both in the editor and the frontend has the potential to make it a time consuming task.

> I don't really get how this can be sticky at the bottom. I don't believe it is. It just behaves normally, like a part of the footer

Thanks for the clarification. I asked this because a certain portion from the bottom of the site title seems to get hidden behind the footer in the design (as the screenshot below). So I thought maybe it got scrolled behind it. So now I understand that there can be overlapping or negative spacing and it's expected. And it'll have to work with the dynamic font size mentioned above


![Image](https://user-images.githubusercontent.com/6820724/199202218-1caec1e9-9ba9-4305-9268-45c6b01ca580.png)

**Comment by Luchadores** [comment]
> Thanks for the clarification. I asked this because a certain portion from the bottom of the site title seems to get hidden behind the footer in the design (as the screenshot below). So I thought maybe it got scrolled behind it. So now I understand that there can be overlapping or negative spacing and it's expected

Got it. No, that's not the case. The title will always be cut a bit at the bottom, as per design. No scrolling involved. 

Thanks, @Imran92 🙏

**Comment by donnapep** [comment]
> Great, just had to make sure that this is an expected behavior because making the font size work that way both in the editor and the frontend has the potential to make it a time consuming task.

@Imran92 If it's time-consuming, we should leave this for a subsequent iteration. There are higher priority tasks that need to be done first. It's also likely a bit of an edge case, and we don't typically optimize for edge cases.

**Comment by Imran92** [comment]
> If it's time-consuming, we should leave this for a subsequent iteration. There are higher priority tasks that need to be done first. It's also likely a bit of an edge case, and we don't typically optimize for edge cases.

Thanks @donnapep ! I've implemented the feature for this behavior for the frontend and it's working as far as I've tested it and published the PR as well ☺ We can leave making the dynamic font work in the editor for a subsequent iteration.

Thank you!

**Comment by donnapep** [comment]
Closed by #70.
