### ISSUE TITLE
Update comments styles

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#6]
Update the comments and comment reply form to match the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020065%3A1078) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020126%3A4278) designs. Example PR [here](https://github.com/Automattic/themes/pull/6520).

Note that we likely won't be able to customize all of the styles using `theme.json`, so we'll need to use custom CSS for some of it.

## Desktop
![Screen Shot 2022-09-28 at 4 18 18 PM](https://user-images.githubusercontent.com/1190420/192881389-58096de4-5404-426e-a420-09a5587ff9d2.jpg)

## Mobile
![Screen Shot 2022-09-30 at 4 08 01 PM](https://user-images.githubusercontent.com/1190420/193348536-b1cbd2a9-f8f2-4182-ad53-8eb2ba891907.jpg)

#### Scenario: Comments & comment reply form
**Given** I've enabled comments for a post
**And** I've added multiple comments for the post, including nested comments
**When** I view the post on the frontend
**Then** the comments and comment reply form look similar to the design on both desktop and mobile.

**Comment by gabrielcaires** [comment]
How are we going to display error messages?

**Comment by donnapep** [comment]
> How are we going to display error messages?

I don't think we'll need to do anything special for that. If someone tries to post a comment without entering a required field for example, WordPress already handles it for us. For example, this is Twenty Twenty Two:

![Screen Shot 2022-09-30 at 4 12 03 PM](https://user-images.githubusercontent.com/1190420/193349053-0edd625f-e1b1-42aa-8820-028d353e6d25.jpg)

**Comment by Luchadores** [comment]
Testing on the front end

**Desktop**
- Vertical spacing seems off, we're also missing the horizontal line in-between content and the comments.
- "Leave a reply" title - uses the wrong font
- Enter the comment field is not styled as in the design and it doesn't spread the whole width of the content
- We're missing Name, Email, and Website fields.

I also tried to post a comment but couldn't do it due to what I assume is a Jurassic Ninja error. Tried refreshing it (which usually solves it) but didn't work.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/10038976/197781983-63a2fc72-e040-43d4-8c2e-7e947e77a5e8.png">

--- 
Code and Design side by side screenshots
![image](https://user-images.githubusercontent.com/10038976/197782068-307ac3b1-14dc-4cd5-821c-0143c80a46bc.png)

**Mobile**

For mobile, I have the same comments as above, with the added difference of getting some space/margin now from the right side of the window (check where the burger menu is on the page). Screenshot attached
![image](https://user-images.githubusercontent.com/10038976/197783161-705482cd-fddb-444b-a623-bed883c1d0dd.png)
